config/routes.rb
Rails.application.routes.draw do

  # admin
  devise_for :admins
  namespace :admin do
    resources :customers,only: [:index,:show,:edit,:update]
  	resources :items,only: [:index,:new,:create,:show,:edit,:update,]
  	get 'top'=>'items#top'
  	resources :genres,only: [:index,:create,:edit,:update, :show]
  	resources :orders,only: [:index,:show,:update] do
  	  member do
        get :current_index
        resource :order_details,only: [:update]
      end
      collection do
        get :today_order_index
      end
    end
  end

  # customer
   devise_for :customers, :controllers => {
    :sessions => 'customers/sessions',
    :registrations => 'customers/registrations',
    :passwords => 'customers/passwords'
   }

  get 'about' => 'customer/items#about'
  root 'customer/items#top'
  get 'contact' => 'customer/customers#contact'

  scope module: :customer do
    resources :items,only: [:index,:show]
    get 'search' => 'items#search'
    get 'customer/edit' => 'customers#edit'
    put 'customer' => 'customers#update'

  	resource :customers,only: [:show] do
  		collection do
  	     get 'unsubscribe'
  	     patch 'withdraw'
  	  end

      resources :cart_items,only: [:index,:update,:create,:destroy] do
        collection do
          delete '/' => 'cart_items#all_destroy'
        end
      end

      resources :orders,only: [:new,:index,:show,:create] do
        collection do
          post 'log'
          get 'thanx'
        end
      end

      resources :addresses,only: [:index,:create,:edit,:update,:destroy]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  
  before_action :authenticate_admin!

  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

	def show
	@customer = Customer.find(params[:id])
	end

	def edit
	@customer = Customer.find(params[:id])
	end

	def update
	@customer = Customer.find(params[:id])
		if @customer.update(customer_params)
		   flash[:success] = "会員情報を変更しました"
		   redirect_to admin_customer_path
		else
			render "edit"
		end

	end

	private
	def customer_params
	  params.require(:customer).permit(:first_name,:last_name,:kana_first_name,:kana_last_name,:postal_code,:residence,:telephone_number,:email,:is_valid)
	end
	
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  before_action :authenticate_admin!

  def index
  		@orders = Order.all.page(params[:page]).per(10)
  end

  def current_index
    @orders = Order.where(customer_id: params[:id]).page(params[:page]).per(10)
    render :index
  end

  def today_order_index
    now = Time.current
    @orders = Order.where(created_at: now.all_day).page(params[:page]).per(10)
    render :index
  end

	def show
		# 注文内容の情報を取得
		@order = Order.find(params[:id])
		# 注文内容の商品を取得
		@order_details = @order.order_details
		
		@total = 0
	end

	def update
		# 注文詳細の特定
		@order = Order.find(params[:id])
		# 注文から紐付く商品の取得
		@order_details = @order.order_details
		# 注文ステータスの更新
		if @order.update(order_params)
		   flash[:success] = "注文ステータスを変更しました"
		   redirect_to admin_order_path(@order)
		else
		   render "show"
		end
		if @order.status == "入金確認" #注文ステータスが入金確認なら下の事をする
	     @order_details.update_all(making_status: 1) #製作ステータスを「製作待ちに」　更新
		end
	end

	private
	def order_params
		  params.require(:order).permit(:status)
	end
	
end

app/controllers/customer/addresses_controller.rb
class Customer::AddressesController < ApplicationController

  before_action :authenticate_customer!


  
   # 配送先一覧/配送先登録画面
    def index
        @shipping_address = Address.new
        @shipping_addresses = current_customer.address
    end

    # 配送先登録ボタン
    def create
        @shipping_address = Address.new(address_params)
        @shipping_address.customer_id = current_customer.id
        if @shipping_address.save
            redirect_to customers_addresses_path
            flash[:success] = "登録しました。"
        else
            @shipping_address = Address.new
            @shipping_addresses = current_customer.addresses
            render 'index'
        end
    end

    # 配送先を削除する
    def destroy
        shipping_address = Address.find(params[:id])
        shipping_address.destroy
        redirect_to customers_addresses_path
    end 

    # 配送先編集ボタン
    def edit
        @shipping_address = Address.find(params[:id])
    end

    # 配送先編集保存ボタン
    def update
        shipping_address = Address.find(params[:id])
        shipping_address.update(address_params)
        redirect_to customers_addresses_path
    end

    private
    def address_params
        params.require(:address).permit(:customer_id, :name, :postal_code, :address)
    end

end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController

  before_action :authenticate_customer!

  # カート商品一覧を表示
  def index
    @cart_items = current_customer.cart_items
    @total_price = @cart_items.sum{|cart_item|cart_item.subtotal}
  end

	# 削除や個数を変更した際、カート商品を再計算する
	def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_item_params)
    redirect_to customers_cart_items_path
	end

	# カート商品を追加する
	def create
	  @genres = Genre.all
    @cart_item = CartItem.new(cart_item_params)
    @cart_item.customer_id = current_customer.id

    if @cart_item.save
      flash[:notice] = "#{@cart_item.item.name}をカートに追加しました。"
      redirect_to customers_cart_items_path
    else
      flash[:alert] = "個数を選択してください"
      render "customer/items/show"
    end
	end

	# カート商品を空ににする
	def all_destroy
    @cart_items = current_customer.cart_items
    @cart_items.destroy_all
    flash[:alert] = "カートの商品を全て削除しました"
    redirect_to customers_cart_items_path
	end

	# カート商品を一つのみ削除
	def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    flash.now[:alert] = "#{@cart_item.item.name}を削除しました"
    redirect_to customers_cart_items_path
	end

  private

  def cart_item_params
    params.require(:cart_item).permit(:amount, :item_id)
  end

end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  
  before_action :authenticate_customer!, except: [:contact]

  def show
    @customer = current_customer
  end

	def unsubscribe
	end

	def withdraw
    @customer = current_customer
    @customer.update(is_deleted: true)

    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
	end

	def edit
    @customer = current_customer
	end

	def update
    @customer = current_customer
		if @customer.update(customer_params)
       flash[:success] = "登録情報を変更しました"
       redirect_to customers_path
    else
       render :edit and return
    end
	end

  def contact
  end

	private

  def customer_params
  	params.require(:customer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :email, :postal_code, :residence, :telephone_numbar)
  end
  
end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController
  
  before_action :authenticate_customer!, only: [:show]

  def top
    @items = Item.all.order(created_at: :asc)
    #=> :asc,古い順 :desc,新しい順　
    @genres = Genre.all
  end

	def index
    @genres = Genre.all
    @items = Item.where(is_active: true).page(params[:page]).per(8)
	end

	def show
    @items = Item.all
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
    @genres = Genre.all
	end

  def about
  end

	private
	def item_params
		parmas.require(:item).permit(:image ,:name, :introduction, :price, :is_active)
	end
	
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController

  before_action :to_log, only: [:show]
  before_action :authenticate_customer!

  def new
  	@order = Order.new
  	@customer = current_customer
  	@addresses = Address.where(customer: current_customer)
  end

	def log
    @cart_items = current_customer.cart_items
    @total_price = @cart_items.sum{|cart_item|cart_item.subtotal}
		@order = Order.new(
      customer: current_customer,
      payment_method: params[:order][:payment_method]
    )


    # addressにresidenceの値がはいっていれば
    if params[:order][:addresses] == "residence"
      @order.postal_code = current_customer.postal_code
      @order.address     = current_customer.residence
      @order.name        = current_customer.last_name +
                           current_customer.first_name

    # addressにshipping_addressesの値がはいっていれば
    elsif params[:order][:addresses] == "shipping_addresses"
      ship = Address.find(params[:order][:address_id])
      @order.postal_code = ship.postal_code
      @order.address     = ship.address
      @order.name        = ship.name

    # addressにnew_addressの値がはいっていれば
    elsif params[:order][:addresses] == "new_address"
      @order.postal_code = params[:order][:postal_code]
      @order.address     = params[:order][:address]
      @order.name        = params[:order][:name]
      @ship = "1"

      # バリデーションがあるならエラーメッセージを表示
      unless @order.valid? == true
        @addresses = Address.where(customer: current_customer)
        render :new
      end
    end
    
    @total = 0
    
	end

	def create
    @order = current_customer.orders.new(order_params)
    @order.save
    flash[:notice] = "ご注文が確定しました。"
    redirect_to thanx_customers_orders_path

    # もし情報入力でnew_addressの場合ShippingAddressに保存
    if params[:order][:ship] == "1"
      current_customer.address.create(address_params)
    end

    # カート商品の情報を注文商品に移動
    cart_items = CartItem.where(customer_id: current_customer.id)
    cart_items.each do |cart_item|
      OrderDetail.create(
        item_id: cart_item.item.id,
        order: @order,
        amount: cart_item.amount,
        price: cart_item.item.price
        )
    end


    # 注文完了後、カート商品を空にする
    cart_items.destroy_all
	end

	def thanx
	end

	def index
    @orders = current_customer.orders
	end

	def show
	  # order特定
	  @order = Order.find(params[:id])
	  # 特定したorderからorder_details全部取得
    @order_details = @order.order_details
    
    @cart_items = current_customer.cart_items
    @total_price = @cart_items.sum{|cart_item|cart_item.subtotal}
    
    @total = 0
	end

  private

  def order_params
    params.require(:order).permit(:postal_code, :address, :name, :payment_method, :total_price, :shipping_cost)
  end

  def address_params
    params.require(:order).permit(:postal_code, :address, :name)
  end

  def to_log
    redirect_to customers_cart_items_path if params[:id] == "log"
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :authenticate_customer!, only: [:edit, :update]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  def edit
    super
     # @customer = current_customer
  end

  # PUT /resource
  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    resource_updated = update_resource(resource, account_update_params)
    yield resource if block_given?
    if resource_updated
      set_flash_message_for_update(resource, prev_unconfirmed_email)
      bypass_sign_in resource, scope: resource_name if sign_in_after_change_password?
      # respond_with resource, location: after_update_path_for(resource)
      flash[:success] = "パスワード変更しました。"
      redirect_to customers_path
    else
      clean_up_passwords resource
      set_minimum_password_length
      redirect_to customers_path
      flash[:alert] = "パスワードを変更できませんでした。"
    end
    # super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def customer_params
    params.require(:customers).permit(:password, :password_confirmation)
  end
  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:password, :password_confirmation])
  # end

  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  def update_resource(resource, params)
    resource.update_with_password(params)
  end

  def after_update_path_for(resource)
    customers_path(resource)
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  
  before_action :reject_customer, only: [:create]

  protected

  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
      if (@customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == false))
        flash[:alert] = "このアカウントは退会済みです。"
        redirect_to new_customer_session_path
      end
    else
    end
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/addresses_helper.rb
module Customer::AddressesHelper
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/views/customer/orders/index.html.erb
<% provide(:title, "注文履歴一覧") %>

<br><br>
<center>
  
  <div class="col-xs-12">
    
    <strong class="information-link"><h3>注文履歴一覧</h3></strong>
    
      <% if @orders.present? %>
      
        <table class="table table-hover table-bordered">
          
          <thead>
            <tr class="info">
              <th><i class="fas fa-calendar-day"></i>注文日</th>
              <th>配送先</th>
              <th>注文商品</th>
              <th>支払金額</th>
              <th>ステータス</th>
              <th>注文詳細</th>
            </tr>
          </thead>
          
          <tbody>
            <% @orders.each do |order| %>
              <tr>
                <td>
    		          <%= order.created_at.strftime('%Y/%m/%d') %>
    		        </td>
    		        <td class="text-left">
    		          <%= order.postal_code %><br>
    		          <%= order.address %><br>
    		          <%= order.name %>
    		        </td>
    		        <td>
    		          <% order.order_details.each do |order_detail| %>
    		          	<%= order_detail.item.name %><br>
    		          <% end %>
    		        </td>
    		        <td class="text-right">
    		          <%= order.total_price %>円
    		        </td>
    		        <td>
    		          <%= order.status %>
    		        </td>
         	      <td>
       	          <%= link_to "注文詳細", customers_order_path(order), class: "glyphicon glyphicon-zoom-in btn btn-dark" %>
       	        </td>
              </tr>
            <% end %>
          </tbody>
          
        </table>
        
      <% else %>
        <p>注文履歴がありません。</p>
      <% end %>
    </div>

    <div class="col-xs-12">
      <%= link_to "戻る", customers_path, class: "glyphicon glyphicon-home btn btn-dark" %>
    </div>
    
</center>
<br><br>

app/views/customer/orders/log.html.erb
<% provide(:title, "注文情報確認") %>

<br><br>
<center>

  <strong><h3>注文情報確認</h3></strong>

  <div class="col-xs-9">

    <% if current_customer.cart_items.present? %>

      <table class="table table-hover table-bordered">

        <thead>
          <tr class="info">
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
          </tr>
        </thead>

        <tbody>
          <% @cart_items.each do |cart_item| %>
            <tr>
              <td class="text-left">
                <%= attachment_image_tag( cart_item.item, :image, size: "55x43", fallback: "no_image.jpg") %>
                <%= cart_item.item.name %>
              </td>
              <td class="text-right">
                ¥<%= cart_item.item.with_tax_price %>
              </td>
              <td class="text-right">
                  <%= cart_item.amount %>
              </td>
              <td class="text-right">
                ¥<%= @total += cart_item.subtotal %>
              </td>
            </tr>
          <% end %>
        </tbody>

      </table>
    </div>

    <div class="col-xs-3">

      <table class="table table-hover table-condensed table-bordered">
          <tr>
            <th class="info">送料</th>
            <td class="text-right col-xs-5">¥<%= @order.shipping_cost %></td>
          </tr>
          <tr>
            <th class="info">商品合計</th>
            <td class="text-right">¥<%= @total %></td>
          </tr>
          <tr>
            <th class="info">請求金額</th>
            <td class="text-right">¥<%= @order.shipping_cost + @total %></td>
          </tr>
      </table>

    </div>

    <div class="col-xs-9">

      <table class="table table-hover table-condensed table-bordered">
        <tr>
          <th  class="info">支払方法</th>
          <td class="text-left">
            <%= @order.payment_method %>
          </td>
        </tr>
        <tr>
          <th  class="info">お届け先</th>
          <td class="text-left">
            <%= "#{@order.postal_code} #{@order.address} #{@order.name}" %>
          </td>
        </tr>
      </table>

      <div class ="col-xs-11">
      <%= form_with model: @order, url: customers_orders_path, method: :post, local: true do |f| %>
        <%= f.hidden_field :customer_id, value: @current_customer.id %>
        <%= f.hidden_field :payment_method, value: @order.payment_method %>
        <%= f.hidden_field :postal_code, value: @order.postal_code %>
        <%= f.hidden_field :address, value: @order.address %>
        <%= f.hidden_field :name, value: @order.name %>
        <%= f.hidden_field :total_price, value: @total_price %>
        <%= f.hidden_field :shipping_cost, value: 800 %>
        <%= link_to "注文情報入力へ戻る", new_customers_order_path, data: {"turbolinks" => false}, class: "btn btn-dark col-xs-3 back" %>
        　　<i class="fas fa-shipping-fast fa-2x"></i>
        <%= f.submit "購入を確定する", class: "btn btn-warning center-block col-xs-5" %>
      <% end %>
      </div>
    <% else %>
        <!-- if カートアイテムがない時 -->
        <p>お客様のショッピングカートに商品はありませんので注文確定ができません。</p>
        <p><%= link_to "商品一覧", items_path %>から商品をお探し下さい。</p>
    <% end %>
  </div>

</center>

<br><br>

app/views/customer/orders/new.html.erb
<% provide(:title, "注文情報入力") %>

<br><br>
<center>
  
  <div class="col-xs-12">
    
    <strong><h3>注文情報入力</h3></strong>
    <br>
    
    <% if current_customer.cart_items.present? %>
    <%= render "layouts/error_messages", resource: @order%>
    
    <div>
      <%= form_with :model => @order, url: log_customers_orders_path, method: :post, local: true  do |f| %>
        <h5 class="fas fa-yen-sign"></i>支払い方法</h5>
          <div>
            <%= f.radio_button :payment_method, Order.payment_methods.key(0) %>
            <%= f.label :payment_method, Order.payment_methods_i18n[:credit_card] %>
          </div>
          <div>
            <%= f.radio_button :payment_method, Order.payment_methods.key(1) %>
            <%= f.label :payment_method, Order.payment_methods_i18n[:transfer]%>
          </div>
        
        <br>

        <h5 class="fas fa-people-carry"></i>お届け先</h5>
          <div>
            <%= f.radio_button :addresses, "residence", checked: true  %>
            <span>ご自身の住所</span><br>
            <%= "〒 #{current_customer.postal_code} #{current_customer.residence}" %>
            <br>
            <%= "#{current_customer.last_name} #{current_customer.first_name}" %>
          </div>
          
          <br>

          <% if @shipping_addresses != [] %>
          <div>
            <%= f.radio_button :addresses, "shipping_addresses" %>
            <span>登録済住所から選択</span><br>
            <%= f.select :address_id, options_from_collection_for_select(Address.all, :id, :address_display) %>
          </div>
          <% end %>
          
          <br>

          <div>
            <%= f.radio_button :addresses, "new_address" %>
            <span>新しいお届け先</span><br>
            <div>
              <%= f.label :"郵便番号(ハイフンなし)", class: "col-sm-4 control-label" %>
              <br>
              <%= f.text_field :postal_code, class: "col-sm-3 form-control-static postal_code" %>
            </div>
            <div>
              <%= f.label :"住所", class: "col-sm-4 control-label" %>
              <br>
              <%= f.text_field :address, class: "col-sm-8 form-control-static address" %>
            </div>
            <div>
              <%= f.label :"宛名", class: "col-sm-4 control-label" %>
              <br>
              <%= f.text_field :name, class: "col-sm-4 form-control-static" %>
            </div>
          </div>
          
          <br>
          
          <div>
            <%= link_to customers_cart_items_path, class: "glyphicon glyphicon-shopping-cart btn btn-dark col-xs-3 cart-back" do %>
             カート(<%= current_customer.cart_items.count %>)へ戻る
            <% end %>
            <%= f.submit "確認画面へ進む", class: "btn btn-dark col-xs-5" %>
          </div>
      <% end %>
    </div>
    <% else %>
      <!-- if カートアイテムがない時 -->
      <p>お客様のショッピングカートに商品はありませんので注文情報の入力ができません。</p>
      <p><%= link_to "商品一覧", items_path, class: "btn btn-warning" %>から商品をお探し下さい。</p>
    <% end %>
  </div>

</center>
<br><br>

app/views/customer/orders/show.html.erb
<% provide(:title, "注文履歴詳細") %>

<br><br>
<center>

<strong class="information-link"><h3>注文履歴詳細</h3></strong>

<div calss="row">
  <% if @order.present? %>

    <div class="col-xs-8">
    	<strong><i class="far fa-user"></i>注文情報</strong>

  	    <table class="table table-bordered table-condensed">
          <tbody>
              <tr>
                <th class="info">注文日</th>
          	  <td class="text-left"><%= @order.created_at.strftime('%Y/%m/%d') %></td>
              </tr>
              <tr>
              　<th class="info">配送先</th>
                <td class="text-left"><%= @order.postal_code %><br>
                	  <%= @order.address %><br>
                	  <%= @order.name %>
                </td>
              </tr>
              <tr>
              　<th class="info">支払方法</th>
                <td class="text-left"><%= @order.payment_method %></td>
              </tr>
              <tr>
                <th class="info">ステータス</th>
                <td class="text-left"><%= @order.status %></td>
              </tr>
          </tbody>
        </table>
    </div>

    <div class="col-xs-7 order-details">
    	<strong><i class="fas fa-store"></i>注文内容</strong>
        <table class="table table-striped table-bordered table-condensed">
        	<thead>
  	      <tr class="info">
  	      	<th class="text-center">商品</th>
  	        <th class="text-center">単価(税込)</th>
  	      	<th class="text-center">個数</th>
  	      	<th class="text-center">小計</th>
  	      </tr>
        	</thead>
        	<tbody>
        	<% @order_details.each do |order_detail| %>
            <tr>
              <td class="text-center"><%= order_detail.item.name %></td>
              <td class="text-center"><%= (order_detail.price*1.1).floor %>円</td> <!-- わからない -->
              <td class="text-center"><%= order_detail.amount %></td>
              <td class="text-center"><%= @total += (order_detail.price*1.1*order_detail.amount).floor %>円</td> <!-- わからない -->
            </tr>
          <% end %>
          </tbody>
        </table>
    </div>

    <div class="col-xs-3 col-xs-offset-1 billing">
      <strong><i class="fas fa-yen-sign"></i>請求情報</strong>
        	<table class="table  table-bordered table-condensed">
            <tr>
              <th class="info">商品合計</th>
              <td class="text-right col-xs-5"><%= @total %>円</td>
            </tr>
            <tr>
              <th class="info">配送料</th>
              <td class="text-right col-xs-5"><%= @order.shipping_cost %>円</td>
            </tr>
            <tr>
              <th class="info">ご請求金額</th>
              <td class="text-right col-xs-5"><%= @total + @order.shipping_cost %>円</td> <!-- わからない -->
            </tr>
        </table>
    </div>

    <% if customer_signed_in? %>
      <%= link_to "注文履歴一覧へ戻る", customers_orders_path, class: "btn btn-dark btn-lg order-index-back" %>
    <% else %>
      <%= link_to "会員詳細へ戻る", admin_customer_path, class: "btn btn-dark order-index-back" %>
    <% end %>
  <% else %>
    <p>注文履歴がありません。</p>
  <% end %>
</div>

</center>
<br><br>

app/views/customer/orders/thanx.html.erb
<% provide(:title, "ありがとうございました！") %>

<br><br>
<center>

<div class=" col-xs-12 center-block">
  <h1 class="text-center">ご注文ありがとうございました！</h1><br>
  <div class="col-xs-7">
    <%= link_to "　注文履歴はこちら　", customers_orders_path, class: "glyphicon glyphicon-folder-open btn btn-dark pull-right" %>
  </div>
</div>

</center>
<br><br>