config/routes.rb
Rails.application.routes.draw do

  # admin
  devise_for :admins
  namespace :admin do
    resources :customers,only: [:index,:show,:edit,:update]
  	resources :items,only: [:index,:new,:create,:show,:edit,:update,]
  	get 'top'=>'items#top'
  	resources :genres,only: [:index,:create,:edit,:update, :show]
  	resources :orders,only: [:index,:show,:update] do
  	  member do
        get :current_index
        resource :order_details,only: [:update]
      end
      collection do
        get :today_order_index
      end
    end
  end

  # customer
   devise_for :customers, :controllers => {
    :sessions => 'customers/sessions',
    :registrations => 'customers/registrations',
    :passwords => 'customers/passwords'
   }

  get 'about' => 'customer/items#about'
  root 'customer/items#top'
  get 'contact' => 'customer/customers#contact'

  scope module: :customer do
    resources :items,only: [:index,:show]
    get 'search' => 'items#search'
    get 'customer/edit' => 'customers#edit'
    put 'customer' => 'customers#update'

  	resource :customers,only: [:show] do
  		collection do
  	     get 'unsubscribe'
  	     patch 'withdraw'
  	  end

      resources :cart_items,only: [:index,:update,:create,:destroy] do
        collection do
          delete '/' => 'cart_items#all_destroy'
        end
      end

      resources :orders,only: [:new,:index,:show,:create] do
        collection do
          post 'log'
          get 'thanx'
        end
      end

      resources :addresses,only: [:index,:create,:edit,:update,:destroy]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  
  belongs_to :customer
	has_many :order_details, dependent: :destroy

	validates :customer_id, :address, :name, :shipping_cost,
			  		:total_price, :payment_method,
			  		presence: true
	validates :postal_code, length: {is: 7}, numericality: { only_integer: true }
	validates :shipping_cost, :total_price, numericality: { only_integer: true }

	enum payment_method: { credit_card: 0, transfer: 1 }
	enum status: {"入金待ち": 0,"入金確認": 1,"製作中": 2,"発送準備中": 3, "発送済み": 4}
	
	
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  before_action :authenticate_admin!

  def index
  		@orders = Order.all.page(params[:page]).per(10)
  end

  def current_index
    @orders = Order.where(customer_id: params[:id]).page(params[:page]).per(10)
    render :index
  end

  def today_order_index
    now = Time.current
    @orders = Order.where(created_at: now.all_day).page(params[:page]).per(10)
    render :index
  end

	def show
		# 注文内容の情報を取得
		@order = Order.find(params[:id])
		# 注文内容の商品を取得
		@order_details = @order.order_details
		
		@total = 0
	end

	def update
		# 注文詳細の特定
		@order = Order.find(params[:id])
		# 注文から紐付く商品の取得
		@order_details = @order.order_details
		# 注文ステータスの更新
		if @order.update(order_params)
		   flash[:success] = "注文ステータスを変更しました"
		   redirect_to admin_order_path(@order)
		else
		   render "show"
		end
		if @order.status == "入金確認" #注文ステータスが入金確認なら下の事をする
	     @order_details.update_all(making_status: 1) #製作ステータスを「製作待ちに」　更新
		end
	end

	private
	def order_params
		  params.require(:order).permit(:status)
	end
	
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController

  before_action :to_log, only: [:show]
  before_action :authenticate_customer!

  def new
  	@order = Order.new
  	@customer = current_customer
  	@addresses = Address.where(customer: current_customer)
  end

	def log
    @cart_items = current_customer.cart_items
    @total_price = @cart_items.sum{|cart_item|cart_item.subtotal}
		@order = Order.new(
      customer: current_customer,
      payment_method: params[:order][:payment_method]
    )


    # addressにresidenceの値がはいっていれば
    if params[:order][:addresses] == "residence"
      @order.postal_code = current_customer.postal_code
      @order.address     = current_customer.residence
      @order.name        = current_customer.last_name +
                           current_customer.first_name

    # addressにshipping_addressesの値がはいっていれば
    elsif params[:order][:addresses] == "shipping_addresses"
      ship = Address.find(params[:order][:address_id])
      @order.postal_code = ship.postal_code
      @order.address     = ship.address
      @order.name        = ship.name

    # addressにnew_addressの値がはいっていれば
    elsif params[:order][:addresses] == "new_address"
      @order.postal_code = params[:order][:postal_code]
      @order.address     = params[:order][:address]
      @order.name        = params[:order][:name]
      @ship = "1"

      # バリデーションがあるならエラーメッセージを表示
      unless @order.valid? == true
        @addresses = Address.where(customer: current_customer)
        render :new
      end
    end
    
    @total = 0
    
	end

	def create
    @order = current_customer.orders.new(order_params)
    @order.save
    flash[:notice] = "ご注文が確定しました。"
    redirect_to thanx_customers_orders_path

    # もし情報入力でnew_addressの場合ShippingAddressに保存
    if params[:order][:ship] == "1"
      current_customer.address.create(address_params)
    end

    # カート商品の情報を注文商品に移動
    cart_items = CartItem.where(customer_id: current_customer.id)
    cart_items.each do |cart_item|
      OrderDetail.create(
        item_id: cart_item.item.id,
        order: @order,
        amount: cart_item.amount,
        price: cart_item.item.price
        )
    end


    # 注文完了後、カート商品を空にする
    cart_items.destroy_all
	end

	def thanx
	end

	def index
    @orders = current_customer.orders
	end

	def show
	  # order特定
	  @order = Order.find(params[:id])
	  # 特定したorderからorder_details全部取得
    @order_details = @order.order_details
    
    @cart_items = current_customer.cart_items
    @total_price = @cart_items.sum{|cart_item|cart_item.subtotal}
    
    @total = 0
	end

  private

  def order_params
    params.require(:order).permit(:postal_code, :address, :name, :payment_method, :total_price, :shipping_cost)
  end

  def address_params
    params.require(:order).permit(:postal_code, :address, :name)
  end

  def to_log
    redirect_to customers_cart_items_path if params[:id] == "log"
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/views/admin/orders/index.html.erb
<% provide(:title, "注文履歴一覧") %>

<br><br>
<center>

  <div class="col-xs-10 col-xs-offset-1">
    <strong><h3>注文一覧</h3></strong>
    <br>


    <div class="order-table">
      <table class="table">
        <thead class="bg-light">
          <tr>
            <th class="text-center">購入日時</th>
            <th class="text-center">購入者</th>
            <th class="text-center">注文個数</th>
            <th class="text-center">注文ステータス</th>
          </tr>
        </thead>

        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td class="text-center">
              	<%= link_to admin_order_path(order), data: {"turbolinks" => false}, :style=>"color:#528fff;"  do %>
									<%= order.created_at %>
								<% end %>
							</td>
              <td class="text-center"><%= full_name(order.customer) %></td>
              <td class="text-center"><%= order.order_details.count %></td>
              <td class="text-center"><%= order.status %></td><!-- わからない -->
            </tr>
            <% end %>
            <%= paginate @orders %>
        </tbody>
      </table>
    </div>
  </div>

</center>
<br><br>

app/views/admin/orders/show.html.erb
<% provide(:title, "注文履歴詳細") %>

<br><br>
<center>

  <div class="col-xs-10 col-xs-offset-1">

    <strong><h3>注文履歴詳細</h3></strong>
    <br>

    <div class="col-xs-7">
    <table class="table">
      <tbody>
      <tr>
        <th class="text-center">購入者</th>
        <td>
        	<%= link_to admin_customer_path(@order.customer) do %>
        		<%= @order.name %>
        	<% end %>
        </td>
      </tr>

      <tr>
        <th class="text-center">配送先</th>
        <td><%= full_address(@order) %></td>
      </tr>

      <tr>
        <th class="text-center">支払方法</th>
        <td><%= @order.payment_method %></td>
      </tr>

      <tr>
        <th class="text-center">注文ステータス</th>
        <td>
        	<%= form_for(@order, url: admin_order_path, method: :patch) do |f| %>
        		<%= f.select :status, Order.statuses.keys, class: "status" %>
        		<%= f.submit '更新'  ,class: "btn btn-dark" %>
        	<% end %>
        </td>
      </tr>
    	</tbody>
 		</table>

  	<table class="table">
    	<thead>
      	<tr>
      	  <th class="text-center">商品名</th>
      	  <th class="text-center">単価（税込）</th>
      	  <th class="text-center">数量</th>
    			<th class="text-center">小計</th>
        	<th class="text-center">製作ステータス</th>
      	</tr>
    	</thead>

    	<tbody>
    	<% if flash[:notice] %>
				<div class="flash">
					<%= flash[:notice] %>
				</div>
	  	<% end %>
			<% @order_details.each do |order_detail| %>
      	<tr>
        	<td class="text-center"><%= order_detail.item.name %></td>
        	<td class="text-center">¥<%= (order_detail.price*1.1).floor %></td>
        	<td class="text-center"><%= order_detail.amount %></td>
        	<td class="text-center">¥<%= @total += (order_detail.price*1.1*order_detail.amount).floor %></td>
        	<td class="text-center">
          	<%= form_for(order_detail, url: admin_order_details_path(order_detail), method: :patch) do |f| %>
          		<%= f.select :making_status, OrderDetail.making_statuses.keys, class: "status" %>
							<%= f.submit '更新'  ,class: "btn btn-dark" %>
          	<% end %>
        	</td>
      	</tr>

    	<% end %>
    	</tbody>
  	</table>
  	</div>

  	<br><br>
    <div class="col-xs-4">
      <table class="table">
        <tbody>

          <tr>
            <td class="text-center">商品合計</td>
            <td>¥<%= @total %></td>
          </tr>

          <tr>
            <td class="text-center">送料</td>
            <td>¥<%= @order.shipping_cost.to_s(:delimited) %></td>
          </tr>

          <tr>
            <td class="text-center">請求合計金額</td>
            <td>¥<%= @order.total_price.to_s(:delimited) %></td>
          </tr>

        </tbody>
      </table>
    </div>

    <div class="col-xs-12">
      <%= link_to "戻る", admin_orders_path, class: "glyphicon glyphicon-home btn btn-dark" %>
    </div>

  </div>

</center>
<br><br>