config/routes.rb
Rails.application.routes.draw do

  # admin
  devise_for :admins
  namespace :admin do
    resources :customers,only: [:index,:show,:edit,:update]
  	resources :items,only: [:index,:new,:create,:show,:edit,:update,]
  	get 'top'=>'items#top'
  	resources :genres,only: [:index,:create,:edit,:update, :show]
  	resources :orders,only: [:index,:show,:update] do
  	  member do
        get :current_index
        resource :order_details,only: [:update]
      end
      collection do
        get :today_order_index
      end
    end
  end

  # customer
   devise_for :customers, :controllers => {
    :sessions => 'customers/sessions',
    :registrations => 'customers/registrations',
    :passwords => 'customers/passwords'
   }

  get 'about' => 'customer/items#about'
  root 'customer/items#top'
  get 'contact' => 'customer/customers#contact'

  scope module: :customer do
    resources :items,only: [:index,:show]
    get 'search' => 'items#search'
    get 'customer/edit' => 'customers#edit'
    put 'customer' => 'customers#update'

  	resource :customers,only: [:show] do
  		collection do
  	     get 'unsubscribe'
  	     patch 'withdraw'
  	  end

      resources :cart_items,only: [:index,:update,:create,:destroy] do
        collection do
          delete '/' => 'cart_items#all_destroy'
        end
      end

      resources :orders,only: [:new,:index,:show,:create] do
        collection do
          post 'log'
          get 'thanx'
        end
      end

      resources :addresses,only: [:index,:create,:edit,:update,:destroy]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  
  before_action :authenticate_admin!

  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

	def show
	@customer = Customer.find(params[:id])
	end

	def edit
	@customer = Customer.find(params[:id])
	end

	def update
	@customer = Customer.find(params[:id])
		if @customer.update(customer_params)
		   flash[:success] = "会員情報を変更しました"
		   redirect_to admin_customer_path
		else
			render "edit"
		end

	end

	private
	def customer_params
	  params.require(:customer).permit(:first_name,:last_name,:kana_first_name,:kana_last_name,:postal_code,:residence,:telephone_number,:email,:is_valid)
	end
	
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  before_action :set_item, only: [:show, :edit, :update]
  before_action :set_genres, only: [:new, :edit, :index, :create, :update]
  before_action :authenticate_admin!

  def top
    now = Time.current
    @orders = Order.where(created_at: now.all_day)
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "新商品を登録しました"
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def show
  end

  def edit
  end

  def update
    if @item.update(item_params)
      flash[:success] = "商品内容をを変更しました"
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :image, :introduction,
       :genre_id, :price, :is_active)
  end

  def set_genres
    @genres = Genre.where(is_valid: true)
  end
  
  
end

app/controllers/customer/addresses_controller.rb
class Customer::AddressesController < ApplicationController

  before_action :authenticate_customer!


  
   # 配送先一覧/配送先登録画面
    def index
        @shipping_address = Address.new
        @shipping_addresses = current_customer.address
    end

    # 配送先登録ボタン
    def create
        @shipping_address = Address.new(address_params)
        @shipping_address.customer_id = current_customer.id
        if @shipping_address.save
            redirect_to customers_addresses_path
            flash[:success] = "登録しました。"
        else
            @shipping_address = Address.new
            @shipping_addresses = current_customer.addresses
            render 'index'
        end
    end

    # 配送先を削除する
    def destroy
        shipping_address = Address.find(params[:id])
        shipping_address.destroy
        redirect_to customers_addresses_path
    end 

    # 配送先編集ボタン
    def edit
        @shipping_address = Address.find(params[:id])
    end

    # 配送先編集保存ボタン
    def update
        shipping_address = Address.find(params[:id])
        shipping_address.update(address_params)
        redirect_to customers_addresses_path
    end

    private
    def address_params
        params.require(:address).permit(:customer_id, :name, :postal_code, :address)
    end

end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController

  before_action :authenticate_customer!

  # カート商品一覧を表示
  def index
    @cart_items = current_customer.cart_items
    @total_price = @cart_items.sum{|cart_item|cart_item.subtotal}
  end

	# 削除や個数を変更した際、カート商品を再計算する
	def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_item_params)
    redirect_to customers_cart_items_path
	end

	# カート商品を追加する
	def create
	  @genres = Genre.all
    @cart_item = CartItem.new(cart_item_params)
    @cart_item.customer_id = current_customer.id

    if @cart_item.save
      flash[:notice] = "#{@cart_item.item.name}をカートに追加しました。"
      redirect_to customers_cart_items_path
    else
      flash[:alert] = "個数を選択してください"
      render "customer/items/show"
    end
	end

	# カート商品を空ににする
	def all_destroy
    @cart_items = current_customer.cart_items
    @cart_items.destroy_all
    flash[:alert] = "カートの商品を全て削除しました"
    redirect_to customers_cart_items_path
	end

	# カート商品を一つのみ削除
	def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    flash.now[:alert] = "#{@cart_item.item.name}を削除しました"
    redirect_to customers_cart_items_path
	end

  private

  def cart_item_params
    params.require(:cart_item).permit(:amount, :item_id)
  end

end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  
  before_action :authenticate_customer!, except: [:contact]

  def show
    @customer = current_customer
  end

	def unsubscribe
	end

	def withdraw
    @customer = current_customer
    @customer.update(is_deleted: true)

    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
	end

	def edit
    @customer = current_customer
	end

	def update
    @customer = current_customer
		if @customer.update(customer_params)
       flash[:success] = "登録情報を変更しました"
       redirect_to customers_path
    else
       render :edit and return
    end
	end

  def contact
  end

	private

  def customer_params
  	params.require(:customer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :email, :postal_code, :residence, :telephone_numbar)
  end
  
end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController
  
  before_action :authenticate_customer!, only: [:show]

  def top
    @items = Item.all.order(created_at: :asc)
    #=> :asc,古い順 :desc,新しい順　
    @genres = Genre.all
  end

	def index
    @genres = Genre.all
    @items = Item.where(is_active: true).page(params[:page]).per(8)
	end

	def show
    @items = Item.all
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
    @genres = Genre.all
	end

  def about
  end

	private
	def item_params
		parmas.require(:item).permit(:image ,:name, :introduction, :price, :is_active)
	end
	
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController

  before_action :to_log, only: [:show]
  before_action :authenticate_customer!

  def new
  	@order = Order.new
  	@customer = current_customer
  	@addresses = Address.where(customer: current_customer)
  end

	def log
    @cart_items = current_customer.cart_items
    @total_price = @cart_items.sum{|cart_item|cart_item.subtotal}
		@order = Order.new(
      customer: current_customer,
      payment_method: params[:order][:payment_method]
    )


    # addressにresidenceの値がはいっていれば
    if params[:order][:addresses] == "residence"
      @order.postal_code = current_customer.postal_code
      @order.address     = current_customer.residence
      @order.name        = current_customer.last_name +
                           current_customer.first_name

    # addressにshipping_addressesの値がはいっていれば
    elsif params[:order][:addresses] == "shipping_addresses"
      ship = Address.find(params[:order][:address_id])
      @order.postal_code = ship.postal_code
      @order.address     = ship.address
      @order.name        = ship.name

    # addressにnew_addressの値がはいっていれば
    elsif params[:order][:addresses] == "new_address"
      @order.postal_code = params[:order][:postal_code]
      @order.address     = params[:order][:address]
      @order.name        = params[:order][:name]
      @ship = "1"

      # バリデーションがあるならエラーメッセージを表示
      unless @order.valid? == true
        @addresses = Address.where(customer: current_customer)
        render :new
      end
    end
    
    @total = 0
    
	end

	def create
    @order = current_customer.orders.new(order_params)
    @order.save
    flash[:notice] = "ご注文が確定しました。"
    redirect_to thanx_customers_orders_path

    # もし情報入力でnew_addressの場合ShippingAddressに保存
    if params[:order][:ship] == "1"
      current_customer.address.create(address_params)
    end

    # カート商品の情報を注文商品に移動
    cart_items = CartItem.where(customer_id: current_customer.id)
    cart_items.each do |cart_item|
      OrderDetail.create(
        item_id: cart_item.item.id,
        order: @order,
        amount: cart_item.amount,
        price: cart_item.item.price
        )
    end


    # 注文完了後、カート商品を空にする
    cart_items.destroy_all
	end

	def thanx
	end

	def index
    @orders = current_customer.orders
	end

	def show
	  # order特定
	  @order = Order.find(params[:id])
	  # 特定したorderからorder_details全部取得
    @order_details = @order.order_details
    
    @cart_items = current_customer.cart_items
    @total_price = @cart_items.sum{|cart_item|cart_item.subtotal}
    
    @total = 0
	end

  private

  def order_params
    params.require(:order).permit(:postal_code, :address, :name, :payment_method, :total_price, :shipping_cost)
  end

  def address_params
    params.require(:order).permit(:postal_code, :address, :name)
  end

  def to_log
    redirect_to customers_cart_items_path if params[:id] == "log"
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :authenticate_customer!, only: [:edit, :update]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  def edit
    super
     # @customer = current_customer
  end

  # PUT /resource
  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    resource_updated = update_resource(resource, account_update_params)
    yield resource if block_given?
    if resource_updated
      set_flash_message_for_update(resource, prev_unconfirmed_email)
      bypass_sign_in resource, scope: resource_name if sign_in_after_change_password?
      # respond_with resource, location: after_update_path_for(resource)
      flash[:success] = "パスワード変更しました。"
      redirect_to customers_path
    else
      clean_up_passwords resource
      set_minimum_password_length
      redirect_to customers_path
      flash[:alert] = "パスワードを変更できませんでした。"
    end
    # super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def customer_params
    params.require(:customers).permit(:password, :password_confirmation)
  end
  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:password, :password_confirmation])
  # end

  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  def update_resource(resource, params)
    resource.update_with_password(params)
  end

  def after_update_path_for(resource)
    customers_path(resource)
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  
  before_action :reject_customer, only: [:create]

  protected

  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
      if (@customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == false))
        flash[:alert] = "このアカウントは退会済みです。"
        redirect_to new_customer_session_path
      end
    else
    end
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/customer/addresses_helper.rb
module Customer::AddressesHelper
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/views/customer/items/_item_each.html.erb
<% if item.genre.is_valid == true %>
  <div class="list-content">
    <div class="item__box">

    <%= link_to item_path(item.id), class: "btn-link", :style=>"color:#0099FF;" do %>
      <div id="img_field" class="product">
        <%= attachment_image_tag(item, :image, size: "180x130", fallback: "no_image.jpg") %>
      </div>
      <p class="products-name">
        <%= item.name %>
      </p>
    <% end %>
    <% if item.is_active == true %>
      <p>¥<%= item.price.to_s(:delimited) %></p>
    <% elsif item.is_active == false %>
      <p class="soldout">売り切れ中</p>
    <% end %>
  	</div>
  </div>
<% end %>

app/views/customer/items/_sidebar.html.erb
    <h4 class="text-center">ジャンルから探す</h4>
    
    <table class="table table-bordered table-hover text-center ec-genre-list" >
      <tr>
        <td>
          <%= link_to "全商品を表示", items_path, class:"ec-genre-list-item" %>
        </td>
      </tr>

      <% genres.each do |genre| %>
        <tr>
          <td>
            <%= link_to genre.name, admin_genre_path(genre.id), class:"ec-genre-list-item"%>
          </td>
        </tr>
     
      <% end %>
    </table>

app/views/customer/items/about.html.erb
<% provide(:title, "サイトについて") %>
<br><br>
<div class="jumbotron">

<div class="container">

        <br><br><br><br><br><br><br>
        <h1 class="text-center text-white"><strong>ABOUT</strong></h1>

    	<br><br>
    	<h4 class="text-center text-white">
            ながのCAKEは全国発送可能なケーキ屋さんです。<br>
            お子様からお年寄りの方までお召し上がりいただけるよう、<br>
            様々なバリエーションをご用意しております。<br>
            また、全国へ発送可能ですので「いつ」でも「どこ」でもご注文いただけます。<br>
            ぜひご注文ください。
        </h4>
        <br><br><br><br><br><br><br>

</div>


</div>

app/views/customer/items/index.html.erb
<% provide(:title, "商品一覧") %>

<br><br>

	<div class="item-center">
		
		<div class="col-md-3">
  		<!-- ジャンルのサイドバーを表示 -->
  		<%= render "customer/items/sidebar", genres: @genres %>
    </div>
		
		<div class="col-xs-offset-1 col-xs-8">
			
			<h3><strong>
			商品一覧
			<span>
				(全<%= @items.total_count %>件中　<%= @items.count %>件)
			</span>
			</strong></h3>
			
			<div class="item-right">
				<% @items.each do |item| %>
				  <% if item.genre.is_valid == true %>
  				<div class="list-content">
  					<div class="item__box">

      			<%= link_to item_path(item.id), class: "btn-link", :style=>"color:#0099FF;" do %>
      			<div id="img_field" class="product">
        			<%= attachment_image_tag(item, :image, size: "180x130", fallback: "no_image.jpg") %>
      			</div>
      			<p class="products-name">
        			<%= item.name %>
      			</p>
      		<% end %>
    			<% if item.is_active == true %>
      			<p>¥<%= item.price.to_s(:delimited) %></p>
    			<% elsif item.is_active == false %>
      			<p class="soldout">売り切れ中</p>
    			<% end %>
    			</div>
  			</div>
				<% end %>
			<% end %>
			</div>
			
			<div class="text-center">
				<%= paginate(@items) %>
			</div>
			
		</div>
	</div>

<br><br>

app/views/customer/items/show.html.erb
<% provide(:title, "商品詳細") %>

<br><br>

<div class="row">
  
    <div class="col-md-3">
    <!-- ジャンルのサイドバーを表示 -->
  		<%= render "customer/items/sidebar", genres: @genres %>
    </div>
  
    
    <div class="show-box">
      
      <div class="show-img">
        <%= attachment_image_tag(@item, :image, size: "340x300", fallback: "no_image.jpg" ) %>
      </div>

    
      <div class="info-box">
        <div class="field product-name">
          <h3><%= @item.name %></h3>
        </div>
        <div class="field">
          <h6><%= @item.introduction %></h6>
        </div>
        <div class="field product-price">
          <h3>¥ <%= (@item.price * 1.1).floor %>
              <span class="tax">(税込)</span>
          </h3>
        </div>
      
        <% if @item.is_active == true %>
          <% if @item.genre.is_valid == true %>
            <%= form_for(@cart_item , url: customers_cart_items_path, method: :post) do |f| %>
              <%= f.hidden_field :item_id, value: @item.id %>
              <%= f.select :amount, options_for_select((1..10).to_a), include_blank: "個数選択" %>
              <%= f.submit "カートに入れる", class: "glyphicon glyphicon-shopping-cart btn btn-dark" %>
            <% end %>
          <% else %>
            <h3>売り切れ中</h3>
          <% end %>
        <% elsif @item.is_active == false %>
          <h3>売り切れ中</h3>
        <% end %>
      </div>
    </div>
</div>

<br><br>

app/views/customer/items/top.html.erb
<% provide(:title, "ホーム") %>

<link href="https://fonts.googleapis.com/css?family=M+PLUS+1p" rel="stylesheet">

<br><br>
<center>
<div id="carouselExampleIndicators" class="carousel carousel-fade slide" data-ride="carousel">

  <!-- スライドさせる画像の設定 -->
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag 'cake1.jpg', class: 'd-block w-100' %>
    </div>
    <div class="carousel-item">
      <%= image_tag 'cake2.jpg', class: 'd-block w-100' %>
    </div>
    <div class="carousel-item">
      <%= image_tag 'cake3.jpg', class: 'd-block w-100' %>
    </div>
  </div><!-- /.carousel-inner -->

  <!-- スライドコントロールの設定 -->
  <!-- "<"のデザイン -->
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
  </a>
  <!-- ">"のデザイン -->
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
  </a>
</div><!-- /.carousel -->
</center>

<br><br><br>

<div class="row">
	
		<div class="col-md-3">
  		<!-- ジャンルのサイドバーを表示 -->
  		<%= render "customer/items/sidebar", genres: @genres %>
    </div>
    
    <div class="col-md-8 offset-md-1">
    	<h4>
				ようこそ、ながのCAKEへ！<br>
			  このサイトは、ケーキ販売のECサイトになります。<br>
			  会員でない方も商品の閲覧はできますが、購入には会員登録が必要になります。
			</h4>
			<br><br>
			<h3 class="toppage-head">新着商品</h3>
			<!-- ランダムに4つ表示されるようになっています -->
			<div class="item-right">
			<% @items.first(5). each do |item| %>
			  <%= render "item_each", item: item %>
			<% end %>
			</div>
			<div class="text-right">
				<%= link_to "全ての商品を見る >", items_path, class: "btn-dark  pull-right" %>
			</div>
		</div>
	
</div>

<br><br>